### ISSUE TITLE
Disciplina em 2019

### ISSUE THREAD

**Issue by beatrizmilz** [leobarone/FLS6397_2018#1]
Olá Dr. Barone, tudo bem? 
Alguns alunos recomendaram essa disciplina. Estou enviando por issue pois não tenho seu email, espero que não tenha problema.
Gostaria de saber se essa disciplina será oferecida em 2019.
Atenciosamente,

Beatriz

**Comment by beatrizmilz** [comment]
O livro Hands-On Programming with R foi disponibilizado gratuitamente recentemente, se quiser disponibilizar o link na lista de referências : 
https://rstudio-education.github.io/hopr/

**Comment by leobarone** [comment]
Oi Beatriz, tudo bem?

É quase certo que eu e Jonathan ofereceremos a disciplina novamente no 1o semestre de 2019, provavelmente às sextas-feiras de manhã.

É importante que você se matricule como aluna de algum programa de pós-graduação da USP/programa conveniado ou como aluna especial. A procura pela disciplina nos últimos anos foi bastante alta e temos negado a participação de ouvintes por limitação de espaço em sala de aula.

O material do curso de 2019 deve ser bastante parecido com o deste repositório. Fique a vontade para utilizá-lo ou repassá-lo.

Obrigado pela dica da disponibilização gratuira do livro!

Abs

**Comment by beatrizmilz** [comment]
Olá! Acompanharei então o processo de matrícula, e espero que dê tudo certo!
Muito obrigada!

**Comment by beatrizmilz** [comment]
Boa tarde Leo!
Me matriculei agora em 2020. Muito obrigada pelas informações!
Vou fechar a issue :)
